//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.SerializationManager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.SerializationManager.Resources.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;system/media/unversioned/audio&quot;: &quot;{d56db3aa-7373-4651-837e-8d3977a0b544}&quot;,
        ///    &quot;system/media/unversioned/doc&quot;: &quot;{16692733-9a61-45e6-b0d4-4c0c06f8dd3c}&quot;,
        ///    &quot;system/media/unversioned/document&quot;: &quot;{777f0c76-d712-46ea-9f40-371acda18a1c}&quot;,
        ///    &quot;system/media/unversioned/docx&quot;: &quot;{7bb0411f-50cd-4c21-ad8f-1fcde7c3affe}&quot;,
        ///    &quot;system/media/unversioned/file&quot;: &quot;{962b53c4-f93b-4df9-9821-415c867b8903}&quot;,
        ///    &quot;system/media/unversioned/flash&quot;: &quot;{9867c0b9-a7be-4d96-ad7e-4ad18109ed20}&quot;,
        ///    &quot;system/media/unvers [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PathToIDMapping {
            get {
                return ResourceManager.GetString("PathToIDMapping", resourceCulture);
            }
        }
    }
}
